#!/usr/bin/env bash
# Configures nginx to add a custom X-Served-By response header
apt-get update -y
apt-get install -y nginx

echo "Holberton School is the best!" > /var/www/html/index.html

if ! grep -q "location /redirect_me" /etc/nginx/sites-enabled/default; then
	sed -i '/listen 80 default_server;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default
fi

echo "Ceci n'est pas une page" > /var/www/html/404.html

if ! grep -q "error_page 404" /etc/nginx/sites-enabled/default; then
	sed -i '/listen 80 default_server;/a\\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default
fi

# shellcheck disable=SC2154
if ! grep -q "add_header X-Served-By" /etc/nginx/sites-enabled/default; then
	sed -i "/listen 80 default_server;/a\\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default
fi

service nginx stop
nginx
