#!/usr/bin/env bash
# Configures nginx so /redirect_me returns a 301 redirect
apt update -y
apt install -y nginx

echo "Holberton School is the best!" > /var/www/html/index.html

sed -i '/listen 80 default_server;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default

service nginx stop
nginx
