#!/usr/bin/env bash
# Configures nginx to serve a custom 404 page
apt update -y
apt install -y nginx

echo "Holberton School is the best!" > /var/www/html/index.html

if ! grep -q "location /redirect_me" /etc/nginx/sites-enabled/default; then
	sed -i '/listen 80 default_server;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default
fi

echo "Ceci n'est pas une page" > /var/www/html/404.html

if ! grep -q "error_page 404" /etc/nginx/sites-enabled/default; then
	sed -i '/listen 80 default_server;/a\\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default
fi

service nginx stop
nginx
